[package]
name = "rsp0f"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
pcap = { version = "0.8" }
colored = { version = "2.0" }
